In [1]:
import pandas as pd
import numpy as np

In [2]:
dictionary = pd.read_csv("outputs/dict/expanded_dict.csv")

In [3]:
dictionary

,integrity,teamwork,innovation,respect,quality
0,responsibility,collaboration,innovation,employee,customer
1,trust,collaborative,innovative,talented,quality
2,responsible,cooperation,efficient,talent,guest
3,transparent,collaborate,creative,job_security,customer_service
4,work_together,cooperative,efficiency,salesperson,wireless
...,...,...,...,...,...
455,NaN,routing_scheduling,NaN,NaN,NaN
456,NaN,production_capability,NaN,NaN,NaN
457,NaN,localize,NaN,NaN,NaN
458,NaN,routing_mobile,NaN,NaN,NaN
459,NaN,distribution_platform,NaN,NaN,NaN

In [6]:
dictionary[["integrity"]].dropna().head(50)

                    integrity
0              responsibility
1                       trust
2                 responsible
3                 transparent
4               work_together
5                transparency
6              accountability
7                    stand_up
8                 intelligent
9                   energized
10                  visionary
11              balancing_act
12                  boil_down
13                 logistical
14               common_sense
15                credibility
16                   meantime
17                stakeholder
18               key_supplier
19       execution_standpoint
20                    deserve
21               learn_lesson
22                  win_-_win
23                    culture
24                   seamless
25              communication
26                  undermine
27                  emotional
28                  conscious
29                     advice
30               keep_promise
31                 compliment
32                  forefront
33                financially
34                   involved
35             professionally
36                distraction
37              intelligently
38                  work_hard
39                    tribute
40             valuable_asset
41                      align
42                     m_real
43                   valuable
44                     reveal
45                     utmost
46                    agility
47                       urge
48  moment_compile_q&a_roster
49               legitimately